logging:
    disable_existing_loggers: false
    formatters:
        console:
            datefmt: '%m/%d/%Y %I:%M:%S %p'
            format: '[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s'
        file:
            datefmt: '%m/%d/%Y %I:%M:%S %p'
            format: '[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
                : %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: console
            level: INFO
            stream: ext://sys.stderr
        file:
            backupCount: 0
            class: logging.handlers.TimedRotatingFileHandler
            filename: logs/mini-transformer.log
            formatter: file
            interval: 1
            level: DEBUG
            when: midnight
    loggers:
        mini_transformer:
            level: DEBUG
            handlers:
            - console
            - file
            propagate: false
    root:
        handlers:
        - console
        - file
        level: ERROR
    version: 1
utils:
    printer:
        line_width: 80
data:
    repo: data/datasets/wmt14/
    tokenizer:
        filepath: models/tokenizer/bpe_tokenizer.json
        vocab_size: 30000
        min_frequency: 2
        show_progress: false
        unk_token: <UNK>
        special_tokens:
        - <PAD>
        - <UNK>
        - <BOS>
        - <EOS>
        - <MASK>
