#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Mini-Transformer                                                                    #
# Version    : 0.1.0                                                                               #
# Python     : 3.11.13                                                                             #
# Filename   : /config.yaml                                                                        #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/mini-transformer                                   #
# ------------------------------------------------------------------------------------------------ #
# Created    : Tuesday August 19th 2025 08:00:33 pm                                                #
# Modified   : Monday August 25th 2025 09:55:05 pm                                                 #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2025 John James                                                                 #
# ================================================================================================ #
logging:
  disable_existing_loggers: false
  formatters:
    console:
      datefmt: '%m/%d/%Y %I:%M:%S %p'
      format: '[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s'
    file:
      datefmt: '%m/%d/%Y %I:%M:%S %p'
      format: '[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
        : %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: INFO
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/mini-transformer.log
      formatter: file
      interval: 1
      level: DEBUG
      when: midnight
  loggers:
    mini_transformer:
      level: DEBUG
      handlers: [console, file]
      propagate: no      
  root:
    handlers:
    - console
    - file
    level: ERROR
  version: 1
# ------------------------------------------------------------------------------------------------ #
utils:
  printer:
    line_width: 80
# ------------------------------------------------------------------------------------------------ #
data:
  repo: tests/data/dataset/
  tokenizer:
    filepath: models/tokenizer/bpe_tokenizer.json
    vocab_size: 30000
    min_frequency: 2
    show_progress: False
    unk_token: <UNK>
    special_tokens:
      - <PAD>
      - <UNK>
      - <BOS>
      - <EOS>
      - <MASK>  


# ------------------------------------------------------------------------------------------------ # 




